<?php $this->plugin('translate')->setTranslatorTextDomain('playgroundcatalog'); ?>
<?php
$fm = $this->flashMessenger()->setNamespace('playgroundcatalog')->getMessages();
if (isset($fm[0]))
{
    print '<span class=>' . $fm[0] . '</span>';
}
?>

<ul class="liste-buttons">
    <li class="btn-admin">
        <a href="<?php echo $this->url('admin/catalog/product/add');?>">
            <?php echo $this->translate('Add new product'); ?>
        </a>
    </li>
</ul>

<h1><?php $this->translate('Product list') ?></h1>

<table class="table">
    <tr>
        <th><?php echo $this->translate('Id'); ?></th>
        <th><?php echo $this->translate('Name'); ?></th>
        <td><?php echo $this->translate('Actions'); ?></td>
    </tr>
    <?php foreach ($this->products as $product): ?>
        <tr>
            <td><?php echo $product->getId() ?></td>
            <td><?php echo $product->getName() ?></td>
            <td>
                <a href='<?php echo $this->url('admin/catalog/product/edit', array('id' => $product->getId())) ?>'><?php echo $this->translate('Edit'); ?></a> | 
                <a href='<?php echo $this->url('admin/catalog/product/remove', array('id' => $product->getId())) ?>'><?php echo $this->translate('Delete'); ?></a>
            </td>
        </tr>
    <?php endforeach; ?>
</table>

<ul class="liste-buttons bottom">
    <li class="btn-admin bottom">
        <a href="<?php echo $this->url('admin/catalog/product/add');?>">
            <?php echo $this->translate('Add new product'); ?>
        </a>
    </li>
</ul>

<?php echo $this->paginationControl($this->products, 'Sliding', 'playground-catalog/pagination', array('type' => $this->type, 'filter' => $this->filter)); ?>
