<?php
$this->plugin('translate')->setTranslatorTextDomain('playgroundcatalog');
$form = $this->form;
$form->prepare();
?>
<?php echo $this->form()->openTag($form) ?>
    <fieldset>
            <?php echo $this->formHidden($form->get('id')); ?>
        <div class="label-input">
            <?php echo $this->formLabel($form->get('name')); ?>
            <?php echo $this->formInput($form->get('name')); ?>
            <?php echo $this->formElementErrors($form->get('name')); ?>
        </div>
    </fieldset>    
<?php echo $this->formButton($form->get('submit')); ?>
<?php echo $this->form()->closeTag() ?>